package jetbrains.mps.lang.editor.diagram.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ExternalFigureReference_BehaviorDescriptor extends AbstractFigureReference_BehaviorDescriptor {
  public List<String> virtual_getFigureParameterNames_1491555030356445722(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_getFigureParameter_1491555030357120840(SNode __thisNode__, String name) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.diagram.structure.ExternalFigureReference";
  }

}
