package jetbrains.mps.closures.test;

/*Generated by MPS */

import junit.framework.TestCase;

public class Parent_Test extends TestCase {

  public int foo;

  public void testStub() {
    // do nothing
  }

}
