package jetbrains.mps.console.blCommand.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class EachLoop_DataFlow extends DataFlowBuilder {
  public EachLoop_DataFlow() {
  }

  public void build(final IOperationContext operationContext, final DataFlowBuilderContext _context) {
    _context.getBuilder().emitLabel("condition");
    _context.getBuilder().emitIfJump(_context.getBuilder().after(_context.getNode()), "r:f56ab982-a3fa-425a-a541-545195484eac(jetbrains.mps.console.blCommand.dataFlow)/752693057588073053");
    _context.getBuilder().build((SNode) SLinkOperations.getTarget(_context.getNode(), "variable", true));
    _context.getBuilder().build((SNode) SLinkOperations.getTarget(_context.getNode(), "body", true));
    _context.getBuilder().emitMayBeUnreachable(new Runnable() {
      public void run() {
        _context.getBuilder().emitJump(_context.getBuilder().label(_context.getNode(), "condition"), "r:f56ab982-a3fa-425a-a541-545195484eac(jetbrains.mps.console.blCommand.dataFlow)/752693057588073065");
      }
    });
  }
}
