package jetbrains.mps.lang.migration.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class OrderDependency_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.migration.structure.OrderDependency";
  }

}
