package jetbrains.mps.baseLanguage.javadoc.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReturnBlockDocTag extends BaseBlockDocTag {
  public static final String concept = "jetbrains.mps.baseLanguage.javadoc.structure.ReturnBlockDocTag";
  public static final String TEXT = "text";

  public ReturnBlockDocTag(SNode node) {
    super(node);
  }

  public String getText() {
    return this.getProperty(ReturnBlockDocTag.TEXT);
  }

  public void setText(String value) {
    this.setProperty(ReturnBlockDocTag.TEXT, value);
  }

  public static ReturnBlockDocTag newInstance(SModel sm, boolean init) {
    return (ReturnBlockDocTag)SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.javadoc.structure.ReturnBlockDocTag", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReturnBlockDocTag newInstance(SModel sm) {
    return ReturnBlockDocTag.newInstance(sm, false);
  }
}
