package jetbrains.mps.bootstrap.structureLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.constraints.IModelConstraints;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.smodel.constraints.ModelConstraintsManager;

public class ConstraintsDescriptor implements IModelConstraints {

  private List<IModelConstraints> myConstraints = new ArrayList<IModelConstraints>();

  public  ConstraintsDescriptor() {
    this.myConstraints.add(new EnumerationMemberDeclaration_externalValue_PropertyConstraint());
    this.myConstraints.add(new EnumerationMemberDeclaration_alias_PropertyConstraint());
    this.myConstraints.add(new AnnotationLinkDeclaration_name_PropertyConstraint());
    this.myConstraints.add(new ConceptDeclaration_extends_ReferentConstraint());
    this.myConstraints.add(new ConceptProperty_conceptPropertyDeclaration_ReferentConstraint());
    this.myConstraints.add(new LinkDeclaration_specializedLink_ReferentConstraint());
    this.myConstraints.add(new ConceptLink_conceptLinkDeclaration_ReferentConstraint());
    this.myConstraints.add(new ReferenceConceptLink_target_ReferentConstraint());
    this.myConstraints.add(new EnumerationDataTypeDeclaration_defaultMember_ReferentConstraint());
  }

  public void unRegisterSelf(ModelConstraintsManager p0) {
    for(IModelConstraints c : this.myConstraints) {
      c.unRegisterSelf(p0);
    }
  }

  public void registerSelf(ModelConstraintsManager p0) {
    for(IModelConstraints c : this.myConstraints) {
      c.registerSelf(p0);
    }
  }

}
