package jetbrains.mps.samples.lambdaCalculus.behavior;

/*Generated by MPS */


public class LetRef_BehaviorDescriptor extends VariableReference_BehaviorDescriptor {
  public LetRef_BehaviorDescriptor() {
  }
}
