package jetbrains.mps.baseLanguage.structure;

/*Generated by MPS  */

import jetbrains.mps.smodel.SNode;

public class LocalVariableDeclarationStatement extends Statement {
  public static String LOCAL_VARIABLE_DECLARATION = "localVariableDeclaration";

  public  LocalVariableDeclarationStatement(SNode node) {
    super(node);
  }

  public LocalVariableDeclaration getLocalVariableDeclaration() {
    return (LocalVariableDeclaration)this.getChild(LocalVariableDeclarationStatement.LOCAL_VARIABLE_DECLARATION);
  }
  public void setLocalVariableDeclaration(LocalVariableDeclaration node) {
    super.setChild(LocalVariableDeclarationStatement.LOCAL_VARIABLE_DECLARATION, node);
  }
}
