package jetbrains.mps.baseLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ThisExpression extends Expression {

  public  ThisExpression(SNode node) {
    super(node);
  }

  public static ThisExpression newInstance(SModel sm, boolean init) {
    return (ThisExpression)SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.ThisExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }
  public static ThisExpression newInstance(SModel sm) {
    return ThisExpression.newInstance(sm, false);
  }
}
