package jetbrains.mps.debugger.api.ui.tool;

/*Generated by MPS */


public class DebuggerToolContent {
  public static final String FRAMES = "Frames";
  public static final String VARIABLES = "Variables";
  public static final String WATCHES = "Watches";
  public DebuggerToolContent() {
  }
}
