package jetbrains.mps.debugger.java.customViewers.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

public class ToProcessMethod_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public ToProcessMethod_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.debugger.java.customViewers.structure.ToProcessMethod";
  }
}
