package jetbrains.mps.lang.behavior.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

@Deprecated
public class SuperNodeExpression_BehaviorDescriptor1 extends Expression_BehaviorDescriptor {
  @Deprecated
  public SuperNodeExpression_BehaviorDescriptor1() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.behavior.structure.SuperNodeExpression";
  }
}
