package jetbrains.mps.lang.editor.intentions;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class IndentLayoutUtil {

  public IndentLayoutUtil() {
  }

  public static void moveToIndentLayoutChildren(SNode node, boolean isLast) {
    if (SNodeOperations.isInstanceOf(node, "jetbrains.mps.lang.editor.structure.CellModel_Collection")) {
      List<SNode> children = SLinkOperations.getTargets(node, "childCellModel", true);
      for(int i = 0 ; i < ListSequence.fromList(children).count() ; i++ ) {
        moveToIndentLayoutChildren(ListSequence.fromList(children).getElement(i), i == ListSequence.fromList(children).count() - 1);
      }
    }
  }

  public static void moveToIndentLayout(SNode node) {
    if (SLinkOperations.getTarget(node, "cellLayout", true) == null || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(node, "cellLayout", true), "jetbrains.mps.lang.editor.structure.CellLayout_Horizontal")) {
      SLinkOperations.setTarget(node, "cellLayout", SConceptOperations.createNewNode("jetbrains.mps.lang.editor.structure.CellLayout_Indent", null), true);
    }
  }

}
