package jetbrains.mps.bash.behavior;

/*Generated by MPS */


public class DivExpression_BehaviorDescriptor extends BinaryArithmeticExpression_BehaviorDescriptor {
  public DivExpression_BehaviorDescriptor() {
  }
}
