package jetbrains.mps.baseLanguage.test;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest4;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

@MPSLaunch
public class myTest_Test extends BaseTransformationTest4 {
  @Test
  public void test_NodeVariableInitializerIsRedundantWarningCheck5348336190814630282() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableInitializerIsRedundantWarningCheck5348336190814630282", true);
  }

  @Test
  public void test_NodeWarningCheck7691029917083376341() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeWarningCheck7691029917083376341", true);
  }

  @Test
  public void test_NodeErrorCheck8333855927568410536() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeErrorCheck8333855927568410536", true);
  }

  @Test
  public void test_NodeVariableHasNotBeenInitializedErrorCheck8333855927568410538() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableHasNotBeenInitializedErrorCheck8333855927568410538", true);
  }

  @Test
  public void test_NodeErrorCheck8333855927568915340() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeErrorCheck8333855927568915340", true);
  }

  @Test
  public void test_NodeVariableCheck8333855927568915813() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableCheck8333855927568915813", true);
  }

  @Test
  public void test_NodeUnusedVariableWarningCheck8333855927568915815() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeUnusedVariableWarningCheck8333855927568915815", true);
  }

  @Test
  public void test_NodeVariableCheck8333855927568916007() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableCheck8333855927568916007", true);
  }

  @Test
  public void test_NodeUnusedVariableWarningCheck8333855927568916009() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeUnusedVariableWarningCheck8333855927568916009", true);
  }

  @Test
  public void test_NodeUnusedVariableWarningCheck7796829026681331726() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeUnusedVariableWarningCheck7796829026681331726", true);
  }

  @Test
  public void test_NodeVariableCheck7796829026681331728() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableCheck7796829026681331728", true);
  }

  @Test
  public void test_NodeWarningCheck8333855927568920104() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeWarningCheck8333855927568920104", true);
  }

  @Test
  public void test_NodeVariableMustBeFinalCheck8428637256413477316() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableMustBeFinalCheck8428637256413477316", true);
  }

  @Test
  public void test_NodeUnknownRuleCheck8428637256413477318() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeUnknownRuleCheck8428637256413477318", true);
  }

  @Test
  public void test_NodeVariableInitializerIsRedundantWarningCheck7796829026681310760() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableInitializerIsRedundantWarningCheck7796829026681310760", true);
  }

  @Test
  public void test_NodeVariableHasNotBeenInitializedErrorCheck7796829026681310762() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableHasNotBeenInitializedErrorCheck7796829026681310762", true);
  }

  @Test
  public void test_NodeUnknownRuleCheck7796829026681310764() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeUnknownRuleCheck7796829026681310764", true);
  }

  @Test
  public void test_NodeCannotAssignValueToFinalCheck8541266710384438015() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeCannotAssignValueToFinalCheck8541266710384438015", true);
  }

  @Test
  public void test_NodeVariableInitializerIsRedundantWarningCheck8333855927548778649() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeVariableInitializerIsRedundantWarningCheck8333855927548778649", true);
  }

  @Test
  public void test_NodeTypeSystemCheck7691029917083389320() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_NodeTypeSystemCheck7691029917083389320", true);
  }

  @Test
  public void test_ErrorMessagesCheck7835233914436668674() throws Throwable {
    this.initTest("${mps_home}", "r:00000000-0000-4000-0000-011c895902c7(jetbrains.mps.baseLanguage.test@tests)");
    this.runTest("jetbrains.mps.baseLanguage.test.myTest_Test$TestBody", "test_ErrorMessagesCheck7835233914436668674", true);
  }

  @MPSLaunch
  public static class TestBody extends BaseTestBody {
    public void test_NodeVariableInitializerIsRedundantWarningCheck5348336190814630282() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("5348336190814630282"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8048812996918091257")});
    }

    public void test_NodeWarningCheck7691029917083376341() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7691029917083376341"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("5348336190814495353")});
    }

    public void test_NodeErrorCheck8333855927568410536() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568410536"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568406295")});
    }

    public void test_NodeVariableHasNotBeenInitializedErrorCheck8333855927568410538() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568410538"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568406334")});
    }

    public void test_NodeErrorCheck8333855927568915340() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568915340"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568914939")});
    }

    public void test_NodeVariableCheck8333855927568915813() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568915813"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568915187")});
    }

    public void test_NodeUnusedVariableWarningCheck8333855927568915815() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568915815"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568915187")});
    }

    public void test_NodeVariableCheck8333855927568916007() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568916007"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568916004")});
    }

    public void test_NodeUnusedVariableWarningCheck8333855927568916009() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568916009"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568916004")});
    }

    public void test_NodeUnusedVariableWarningCheck7796829026681331726() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7796829026681331726"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568916102")});
    }

    public void test_NodeVariableCheck7796829026681331728() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7796829026681331728"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568916102")});
    }

    public void test_NodeWarningCheck8333855927568920104() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927568920104"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927568920101")});
    }

    public void test_NodeVariableMustBeFinalCheck8428637256413477316() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8428637256413477316"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927569230357")});
    }

    public void test_NodeUnknownRuleCheck8428637256413477318() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8428637256413477318"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8333855927569230357")});
    }

    public void test_NodeVariableInitializerIsRedundantWarningCheck7796829026681310760() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7796829026681310760"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("7835233914436667239")});
    }

    public void test_NodeVariableHasNotBeenInitializedErrorCheck7796829026681310762() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7796829026681310762"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("7835233914436667239")});
    }

    public void test_NodeUnknownRuleCheck7796829026681310764() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7796829026681310764"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("7835233914436667239")});
    }

    public void test_NodeCannotAssignValueToFinalCheck8541266710384438015() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8541266710384438015"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8541266710384287431")});
    }

    public void test_NodeVariableInitializerIsRedundantWarningCheck8333855927548778649() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("8333855927548778649"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("7691029917083387026")});
    }

    public void test_NodeTypeSystemCheck7691029917083389320() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7691029917083389320"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("7691029917083385235")});
    }

    public void test_ErrorMessagesCheck7835233914436668674() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("7835233914436668674"), "jetbrains.mps.lang.test.structure.NodeCheckOperation");
      BehaviorReflection.invokeVirtual(Void.class, operation, "virtual_perform_245688835340859348", new Object[]{this.getRealNodeById("8048812996918011290")});
    }
  }
}
