package jetbrains.mps.lang.plugin.standalone.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ProjectPluginDeclaration_Behavior {
  public static String call_getGeneratedName_481983775135178936(SNode __thisNode__) {
    return ProjectPluginDeclaration__BehaviorDescriptor.getGeneratedName_idqKmr2orM2S(__thisNode__);
  }
  public static String call_getGeneratedClassFQName_481983775135178947(SNode __thisNode__) {
    return ProjectPluginDeclaration__BehaviorDescriptor.getGeneratedClassFQName_idqKmr2orM33(__thisNode__);
  }
}
