package jetbrains.mps.baseLanguage.money.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.runtime.StaticScope;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Map;
import java.util.HashMap;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptMoneyCreator = new ConceptDescriptorBuilder("jetbrains.mps.baseLanguage.money.structure.MoneyCreator", MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x11472ff5968L)).super_("jetbrains.mps.baseLanguage.structure.AbstractCreator").super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab844af9bL)).parents("jetbrains.mps.baseLanguage.structure.AbstractCreator").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab844af9bL)).childDescriptors(new ConceptDescriptorBuilder.Link(1187344039345L, "amount", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), false, false, false), new ConceptDescriptorBuilder.Link(1187344093002L, "currency", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), false, false, false)).children(new String[]{"amount", "currency"}, new boolean[]{false, false}).alias("Money", "money type constructor").staticScope(StaticScope.NONE).create();
  /*package*/ final ConceptDescriptor myConceptMoneyGetAmountMethodCall = new ConceptDescriptorBuilder("jetbrains.mps.baseLanguage.money.structure.MoneyGetAmountMethodCall", MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b5d60L)).super_("jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall").super_(MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L)).parents("jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall").parentIds(MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L)).alias(". amount", "").staticScope(StaticScope.NONE).create();
  /*package*/ final ConceptDescriptor myConceptMoneyGetCurrencyMethodCall = new ConceptDescriptorBuilder("jetbrains.mps.baseLanguage.money.structure.MoneyGetCurrencyMethodCall", MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740c6f9bL)).super_("jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall").super_(MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L)).parents("jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall").parentIds(MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L)).alias(". currency", "").staticScope(StaticScope.NONE).create();
  /*package*/ final ConceptDescriptor myConceptMoneyIsZeroMethodCall = new ConceptDescriptorBuilder("jetbrains.mps.baseLanguage.money.structure.MoneyIsZeroMethodCall", MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x11483863450L)).super_("jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall").super_(MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L)).parents("jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall").parentIds(MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L)).alias(". isZero", "").staticScope(StaticScope.NONE).create();
  /*package*/ final ConceptDescriptor myConceptMoneyLiteral = new ConceptDescriptorBuilder("jetbrains.mps.baseLanguage.money.structure.MoneyLiteral", MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x1144ae7606aL)).super_("jetbrains.mps.baseLanguage.structure.Expression").super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1186667945792L, "currency"), new ConceptDescriptorBuilder.Prop(1186667962877L, "amount")).properties("currency", "amount").staticScope(StaticScope.NONE).create();
  /*package*/ final ConceptDescriptor myConceptMoneyMethodCall = new ConceptDescriptorBuilder("jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall", MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L)).super_("jetbrains.mps.baseLanguage.structure.Expression").super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).childDescriptors(new ConceptDescriptorBuilder.Link(1187358164451L, "instance", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), false, false, false)).children(new String[]{"instance"}, new boolean[]{false}).abstract_().staticScope(StaticScope.NONE).create();
  /*package*/ final ConceptDescriptor myConceptMoneyType = new ConceptDescriptorBuilder("jetbrains.mps.baseLanguage.money.structure.MoneyType", MetaIdFactory.conceptId(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x1144b05194dL)).super_("jetbrains.mps.baseLanguage.structure.Type").super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506dL)).parents("jetbrains.mps.baseLanguage.structure.Type").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506dL)).alias("Money", "").staticScope(StaticScope.NONE).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptMoneyCreator, myConceptMoneyGetAmountMethodCall, myConceptMoneyGetCurrencyMethodCall, myConceptMoneyIsZeroMethodCall, myConceptMoneyLiteral, myConceptMoneyMethodCall, myConceptMoneyType);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = concept;
      Integer preIndex = indices_1htk8d_a0l.get(cncpt);
      int switchIndex = (preIndex == null ? -1 : preIndex);
      switch (switchIndex) {
        case 0:
          if (true) {
            return myConceptMoneyCreator;
          }
          break;
        case 1:
          if (true) {
            return myConceptMoneyGetAmountMethodCall;
          }
          break;
        case 2:
          if (true) {
            return myConceptMoneyGetCurrencyMethodCall;
          }
          break;
        case 3:
          if (true) {
            return myConceptMoneyIsZeroMethodCall;
          }
          break;
        case 4:
          if (true) {
            return myConceptMoneyLiteral;
          }
          break;
        case 5:
          if (true) {
            return myConceptMoneyMethodCall;
          }
          break;
        case 6:
          if (true) {
            return myConceptMoneyType;
          }
          break;
        default:
          // default 
      }
    }
    return null;
  }
  private static Map<SAbstractConcept, Integer> buildConceptIndices(SAbstractConcept... concepts) {
    HashMap<SAbstractConcept, Integer> res = new HashMap<SAbstractConcept, Integer>();
    int counter = 0;
    for (SAbstractConcept c : concepts) {
      res.put(c, counter++);
    }
    return res;
  }
  private static final Map<SAbstractConcept, Integer> indices_1htk8d_a0l = buildConceptIndices(MetaAdapterFactory.getConcept(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x11472ff5968L, "jetbrains.mps.baseLanguage.money.structure.MoneyCreator"), MetaAdapterFactory.getConcept(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b5d60L, "jetbrains.mps.baseLanguage.money.structure.MoneyGetAmountMethodCall"), MetaAdapterFactory.getConcept(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740c6f9bL, "jetbrains.mps.baseLanguage.money.structure.MoneyGetCurrencyMethodCall"), MetaAdapterFactory.getConcept(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x11483863450L, "jetbrains.mps.baseLanguage.money.structure.MoneyIsZeroMethodCall"), MetaAdapterFactory.getConcept(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x1144ae7606aL, "jetbrains.mps.baseLanguage.money.structure.MoneyLiteral"), MetaAdapterFactory.getConcept(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x114740b1673L, "jetbrains.mps.baseLanguage.money.structure.MoneyMethodCall"), MetaAdapterFactory.getConcept(0xf43135f9b8334685L, 0x8d26ffb6c8215f72L, 0x1144b05194dL, "jetbrains.mps.baseLanguage.money.structure.MoneyType"));
}
