package jetbrains.mps.ide.migration;

/*Generated by MPS */


public interface MigrationManager {
  public boolean isMigrationRequired();
  public MigrationManager.MigrationState nextStep();
  public static interface MigrationState {
    public static interface Step extends MigrationManager.MigrationState {
      public String getDescription();
      public boolean execute();
    }
    public static interface Conflict extends MigrationManager.MigrationState {
      public Iterable<ScriptApplied> getConflictingScripts();
      public boolean forceExecution(ScriptApplied next);
    }
    public static interface Finished extends MigrationManager.MigrationState {
    }
    public static interface Error extends MigrationManager.MigrationState {
      public String getErrorMessage();
      public Throwable cause();
    }
  }
}
