package jetbrains.mps.lang.editor.diagram.tests;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

@MPSLaunch
public class DeleteDiagramNode_Test extends BaseTransformationTest {
  @Test
  public void test_DeleteDiagramNode() throws Throwable {
    initTest("${mps_home}", "r:e41d7e03-7ef3-4161-a48a-e48d8152e422(jetbrains.mps.lang.editor.diagram.tests@tests)");
    runTest("jetbrains.mps.lang.editor.diagram.tests.DeleteDiagramNode_Test$TestBody", "testMethod", false);
  }

  @MPSLaunch
  public static class TestBody extends BaseEditorTestBody {
    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("5003005296038309041", "5003005296038309154");
      pressKeys(ListSequence.fromListAndArray(new ArrayList<String>(), " DELETE"));
    }
  }
}
