package jetbrains.mps.lang.generator.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

public class LoopMacro_BehaviorDescriptor extends SourceSubstituteMacro_BehaviorDescriptor implements ContextVariableProvider_BehaviorDescriptor {
  public List<SNode> virtual_contextVariables_7430509679011531975(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_getInputNodeTypeInsideOfMacro_1213877290799(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_suppress_3393165121846091591(SNode __thisNode__, SNode child) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.generator.structure.LoopMacro";
  }

}
