package jetbrains.mps.lang.generator.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;

public class StubRoot_MappingRule_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "applicableConcept", createIntegerConstant_7p9iqz_a0a0a0(), false);
    SLinkOperations.setTarget(thisNode, "template", createIntegerConstant_7p9iqz_a0a1a0(), false);
  }
  private static SNode createIntegerConstant_7p9iqz_a0a0a0() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode n1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.IntegerConstant", null, false);
    n1.setProperty("value", "" + 0);
    return n1;
  }
  private static SNode createIntegerConstant_7p9iqz_a0a1a0() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode n1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.IntegerConstant", null, false);
    n1.setProperty("value", "" + 0);
    return n1;
  }
}
