package jetbrains.mps.lang.typesystem.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunctionParameter_BehaviorDescriptor;

public class Operation_parameter_BehaviorDescriptor extends ConceptFunctionParameter_BehaviorDescriptor {
  public Operation_parameter_BehaviorDescriptor() {
  }
}
