package jetbrains.mps.make.resources.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface Resource extends INodeAdapter {
  public static final String concept = "jetbrains.mps.make.resources.structure.Resource";
}
